server:
    port: 8081
spring:
    application:
        name: social_media
    datasource:
        password: Manit@123
        url: jdbc:mysql://localhost:3306/studentdb
        username: root
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true